sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['libssl-dev', 'curl', 'libprotobuf-dev', 'protobuf-compiler']

compiler:
    - gcc

language: cpp

script:
    - make
